version: "3.9"

services:
  mcp-atlassian:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    container_name: mcp-atlassian
    env_file:
      - .env
    ports:
      - "${MCP_SERVER_PORT:-8080}:8080"
    networks:
      - mcp-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - mcp-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    env_file:
      - .env
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - mcp-network

volumes:
  postgres-data:
  qdrant-data:

networks:
  mcp-network:
    driver: bridge
