version: "3.9"

services:
  mcp-atlassian:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    container_name: mcp-atlassian
    env_file:
      - .env
    ports:
      - "${JIRA_MCP_SERVER_PORT:-8010}:8000"
    networks:
      - mcp-network
    command: ["--transport=streamable-http"]

  mcp-google:
    build:
      context: .
      dockerfile: ai/agents/mcp/google_mcp/Dockerfile
    container_name: mcp-google
    env_file:
      - .env
    environment:
      - TOOLS=gmail drive calendar
    ports:
      - "8000:8000"
    networks:
      - mcp-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 5s
    networks:
      - mcp-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    env_file:
      - .env
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - mcp-network

  langfuse:
    image: langfuse/langfuse:3
    container_name: langfuse
    env_file:
      - .env
    environment:
      - DATABASE_URL=${LANGFUSE_DATABASE_URL}
      - NEXTAUTH_URL=${LANGFUSE_NEXTAUTH_URL:-http://localhost:${LANGFUSE_PORT:-3000}}
      - NEXTAUTH_SECRET=${LANGFUSE_NEXTAUTH_SECRET}
      - SALT=${LANGFUSE_SALT}
      - ENCRYPTION_KEY=${LANGFUSE_ENCRYPTION_KEY}
      - CLICKHOUSE_URL=http://langfuse-clickhouse:8123
      - CLICKHOUSE_USER=${LANGFUSE_CLICKHOUSE_USER:-clickhouse}
      - CLICKHOUSE_PASSWORD=${LANGFUSE_CLICKHOUSE_PASSWORD:-clickhouse}
      - CLICKHOUSE_MIGRATION_URL=clickhouse://${LANGFUSE_CLICKHOUSE_USER:-clickhouse}:${LANGFUSE_CLICKHOUSE_PASSWORD:-clickhouse}@langfuse-clickhouse:9000
      - CLICKHOUSE_CLUSTER_ENABLED=false
      - REDIS_HOST=langfuse-redis
      - REDIS_PORT=6379
      - REDIS_AUTH=${LANGFUSE_REDIS_PASSWORD:-redis}
    depends_on:
      postgres:
        condition: service_healthy
      langfuse-redis:
        condition: service_started
      langfuse-clickhouse:
        condition: service_started
    ports:
      - "${LANGFUSE_PORT:-3000}:3000"
    networks:
      - mcp-network

  langfuse-worker:
    image: langfuse/langfuse-worker:3
    container_name: langfuse-worker
    env_file:
      - .env
    environment:
      - DATABASE_URL=${LANGFUSE_DATABASE_URL}
      - NEXTAUTH_URL=${LANGFUSE_NEXTAUTH_URL:-http://langfuse:3000}
      - SALT=${LANGFUSE_SALT}
      - ENCRYPTION_KEY=${LANGFUSE_ENCRYPTION_KEY}
      - CLICKHOUSE_URL=http://langfuse-clickhouse:8123
      - CLICKHOUSE_USER=${LANGFUSE_CLICKHOUSE_USER:-clickhouse}
      - CLICKHOUSE_PASSWORD=${LANGFUSE_CLICKHOUSE_PASSWORD:-clickhouse}
      - CLICKHOUSE_MIGRATION_URL=clickhouse://${LANGFUSE_CLICKHOUSE_USER:-clickhouse}:${LANGFUSE_CLICKHOUSE_PASSWORD:-clickhouse}@langfuse-clickhouse:9000
      - CLICKHOUSE_CLUSTER_ENABLED=false
      - REDIS_HOST=langfuse-redis
      - REDIS_PORT=6379
      - REDIS_AUTH=${LANGFUSE_REDIS_PASSWORD:-redis}
    depends_on:
      postgres:
        condition: service_healthy
      langfuse-redis:
        condition: service_started
      langfuse-clickhouse:
        condition: service_started
    networks:
      - mcp-network

  langfuse-redis:
    image: redis:7-alpine
    container_name: langfuse-redis
    command: ["redis-server", "--requirepass", "${LANGFUSE_REDIS_PASSWORD:-redis}"]
    env_file:
      - .env
    ports:
      - "${LANGFUSE_REDIS_PORT:-6379}:6379"
    networks:
      - mcp-network

  langfuse-clickhouse:
    image: clickhouse/clickhouse-server:23.3
    container_name: langfuse-clickhouse
    env_file:
      - .env
    environment:
      - CLICKHOUSE_DB=${LANGFUSE_CLICKHOUSE_DB:-default}
      - CLICKHOUSE_USER=${LANGFUSE_CLICKHOUSE_USER:-clickhouse}
      - CLICKHOUSE_PASSWORD=${LANGFUSE_CLICKHOUSE_PASSWORD:-clickhouse}
    ports:
      - "${LANGFUSE_CLICKHOUSE_HTTP_PORT:-8123}:8123"
      - "${LANGFUSE_CLICKHOUSE_NATIVE_PORT:-9000}:9000"
    volumes:
      - langfuse-clickhouse-data:/var/lib/clickhouse
      - langfuse-clickhouse-logs:/var/log/clickhouse-server
    networks:
      - mcp-network

volumes:
  postgres-data:
  qdrant-data:
  langfuse-clickhouse-data:
  langfuse-clickhouse-logs:


networks:
  mcp-network:
    driver: bridge
