[agent]
model = "openai:gpt-4.1"

[servers.base.time]
transport = "stdio"
command = "python"
args = ["-m", "ai.agents.mcp.time_server"]

[servers.base.memory]
transport = "stdio"
command = "python"
args = ["-m", "ai.agents.mcp.memory_agent"]

[servers.base.google]
transport = "streamable_http"
url = "http://localhost:8000/mcp"

[servers.platforms.jira]
transport = "streamable_http"
url = "http://localhost:8010/mcp"

[servers.platforms.asana]
transport = "stdio"
command = "npx"
args = ["-y", "@roychri/mcp-server-asana"]

[tool_approvals.asana_add_task_dependencies]
summary = "Approve editing Asana task dependencies?"
context = "The agent will change dependency relationships for the specified task."
allow_edit = true
allow_reject = true

[tool_approvals.asana_add_task_dependents]
summary = "Approve editing Asana task dependents?"
context = "The agent will update which tasks depend on the specified task."
allow_edit = true
allow_reject = true

[tool_approvals.asana_create_task]
summary = "Approve creatong an Asana task?"
context = "The agent will modify fields on an existing Asana task."
allow_edit = true
allow_reject = true

[tool_approvals.asana_delete_project_status]
summary = "Approve deleting an Asana project status update?"
context = "The agent will permanently remove the selected project status update."
allow_edit = false
allow_reject = true

[tool_approvals.asana_set_parent_for_task]
summary = "Approve reorganizing Asana task hierarchy?"
context = "The agent will change the parent or position of the specified task."
allow_edit = true
allow_reject = true

[tool_approvals.asana_update_task]
summary = "Approve updating an Asana task?"
context = "The agent will modify fields on an existing Asana task."
allow_edit = true
allow_reject = true

[tool_approvals.batch_modify_gmail_message_labels]
summary = "Approve bulk Gmail label changes?"
context = "The agent will modify labels across multiple Gmail messages in one operation."
allow_edit = true
allow_reject = true

[tool_approvals.batch_update_doc]
summary = "Approve running batch updates on a Google Doc?"
context = "The agent will execute multiple structural changes on the document in a single request."
allow_edit = true
allow_reject = true

[tool_approvals.batch_update_presentation]
summary = "Approve bulk updates to a Google Slides presentation?"
context = "The agent will apply structural changes to the presentation via the Slides API."
allow_edit = true
allow_reject = true

[tool_approvals.clear_completed_tasks]
summary = "Approve clearing completed Google Tasks?"
context = "The agent will delete all completed tasks in the specified list."
allow_edit = true
allow_reject = true

[tool_approvals.clear_langgraph_thread]
summary = "Approve clearing the agent conversation history?"
context = "This will remove stored LangGraph checkpoints for this Slack conversation so future interactions start fresh."
allow_edit = false
allow_reject = true

[tool_approvals.create_doc]
summary = "Approve creating a Google Doc?"
context = "The agent will create a new Google Document in your Drive."
allow_edit = true
allow_reject = true

[tool_approvals.create_document_comment]
summary = "Approve adding a Google Doc comment?"
context = "The agent will leave a new comment in the document."
allow_edit = true
allow_reject = true

[tool_approvals.create_drive_file]
summary = "Approve creating a Google Drive file?"
context = "The agent will create or upload a file in Google Drive."
allow_edit = true
allow_reject = true

[tool_approvals.create_event]
summary = "Approve creating a Google Calendar event?"
context = "The agent will add a new event to your Google Calendar via the Google MCP server."
allow_edit = true
allow_reject = true

[tool_approvals.create_form]
summary = "Approve creating a Google Form?"
context = "The agent will generate a new Google Form in your account."
allow_edit = true
allow_reject = true

[tool_approvals.create_presentation]
summary = "Approve creating a Google Slides presentation?"
context = "The agent will create a new Google Slides deck in your Drive."
allow_edit = true
allow_reject = true

[tool_approvals.create_presentation_comment]
summary = "Approve adding a Google Slides comment?"
context = "The agent will add a new comment on the specified presentation slide."
allow_edit = true
allow_reject = true

[tool_approvals.create_sheet]
summary = "Approve adding a sheet to a Google Spreadsheet?"
context = "The agent will insert a new tab within an existing spreadsheet."
allow_edit = true
allow_reject = true

[tool_approvals.create_spreadsheet]
summary = "Approve creating a Google Spreadsheet?"
context = "The agent will create a new Google Sheet in your Drive."
allow_edit = true
allow_reject = true

[tool_approvals.create_spreadsheet_comment]
summary = "Approve adding a Google Sheet comment?"
context = "The agent will leave a comment on the specified spreadsheet cell range."
allow_edit = true
allow_reject = true

[tool_approvals.create_table_with_data]
summary = "Approve creating a data table in a Google Doc?"
context = "The agent will build and populate a table within the document."
allow_edit = true
allow_reject = true

[tool_approvals.create_task]
summary = "Approve creating a Google Task?"
context = "The agent will add a new task to the specified task list."
allow_edit = true
allow_reject = true

[tool_approvals.create_task_list]
summary = "Approve creating a Google Tasks list?"
context = "The agent will create a new task list in Google Tasks."
allow_edit = true
allow_reject = true

[tool_approvals.delete_event]
summary = "Approve deleting a Google Calendar event?"
context = "The agent will remove the specified event from Google Calendar."
allow_edit = true
allow_reject = true

[tool_approvals.delete_task]
summary = "Approve deleting a Google Task?"
context = "The agent will remove the specified task from Google Tasks."
allow_edit = true
allow_reject = true

[tool_approvals.delete_task_list]
summary = "Approve deleting a Google Tasks list?"
context = "The agent will remove the specified task list and its tasks from Google Tasks."
allow_edit = true
allow_reject = true

[tool_approvals.draft_gmail_message]
summary = "Approve drafting a Gmail message?"
context = "The agent will create a draft email in your Gmail account."
allow_edit = true
allow_reject = true

[tool_approvals.export_doc_to_pdf]
summary = "Approve exporting a Google Doc to PDF?"
context = "The agent will generate a PDF from the document and upload it to Google Drive."
allow_edit = true
allow_reject = true

[tool_approvals.find_and_replace_doc]
summary = "Approve running find and replace in a Google Doc?"
context = "The agent will search for text and replace it within a Google Document."
allow_edit = true
allow_reject = true

[tool_approvals.insert_doc_elements]
summary = "Approve inserting structured elements into a Google Doc?"
context = "The agent will insert tables, lists, or other structural elements into the document."
allow_edit = true
allow_reject = true

[tool_approvals.insert_doc_image]
summary = "Approve adding an image to a Google Doc?"
context = "The agent will insert an image into the specified Google Document."
allow_edit = true
allow_reject = true

[tool_approvals.jira_add_comment]
summary = "Approve posting a Jira comment?"
context = "The agent will add a comment to the specified Jira issue on your behalf."
allow_edit = true
allow_reject = true

[tool_approvals.jira_create_issue]
summary = "Approve creating a new Jira issue?"
context = "The agent will draft and submit a new Jira issue via the Jira MCP server."
allow_edit = true
allow_reject = true

[tool_approvals.jira_create_issue_link]
summary = "Approve linking Jira issues?"
context = "The agent will create a relationship link between Jira issues."
allow_edit = true
allow_reject = true

[tool_approvals.jira_transition_issue]
summary = "Approve moving a Jira issue to a new status?"
context = "The agent will trigger a workflow transition for the selected issue."
allow_edit = true
allow_reject = true

[tool_approvals.jira_update_issue]
summary = "Approve updating an existing Jira issue?"
context = "The agent plans to modify fields on an existing Jira issue."
allow_edit = true
allow_reject = true

[tool_approvals.manage_gmail_label]
summary = "Approve managing Gmail labels?"
context = "The agent will create, update, or delete labels in Gmail."
allow_edit = true
allow_reject = true

[tool_approvals.modify_doc_text]
summary = "Approve editing Google Doc text?"
context = "The agent will modify the text content of a Google Document."
allow_edit = true
allow_reject = true

[tool_approvals.modify_event]
summary = "Approve updating a Google Calendar event?"
context = "The agent will change details on an existing Google Calendar event."
allow_edit = true
allow_reject = true

[tool_approvals.modify_gmail_message_labels]
summary = "Approve updating Gmail message labels?"
context = "The agent will change label assignments on existing Gmail messages."
allow_edit = true
allow_reject = true

[tool_approvals.modify_sheet_values]
summary = "Approve modifying values in a Google Sheet?"
context = "The agent will write, update, or clear data within the specified spreadsheet range."
allow_edit = true
allow_reject = true

[tool_approvals.move_task]
summary = "Approve moving a Google Task?"
context = "The agent will reposition the task within its list or move it to another list."
allow_edit = true
allow_reject = true

[tool_approvals.reply_to_document_comment]
summary = "Approve replying to a Google Doc comment?"
context = "The agent will post a reply to an existing comment in the document."
allow_edit = true
allow_reject = true

[tool_approvals.reply_to_presentation_comment]
summary = "Approve replying to a Google Slides comment?"
context = "The agent will respond to an existing comment thread in the presentation."
allow_edit = true
allow_reject = true

[tool_approvals.reply_to_spreadsheet_comment]
summary = "Approve replying to a Google Sheet comment?"
context = "The agent will post a reply within a spreadsheet comment thread."
allow_edit = true
allow_reject = true

[tool_approvals.resolve_document_comment]
summary = "Approve resolving a Google Doc comment?"
context = "The agent will mark a comment thread as resolved in the document."
allow_edit = true
allow_reject = true

[tool_approvals.resolve_presentation_comment]
summary = "Approve resolving a Google Slides comment?"
context = "The agent will mark a presentation comment thread as resolved."
allow_edit = true
allow_reject = true

[tool_approvals.resolve_spreadsheet_comment]
summary = "Approve resolving a Google Sheet comment?"
context = "The agent will mark a spreadsheet comment thread as resolved."
allow_edit = true
allow_reject = true

[tool_approvals.send_gmail_message]
summary = "Approve sending a Gmail message?"
context = "The agent will send an email through your Gmail account."
allow_edit = true
allow_reject = true

[tool_approvals.send_message]
summary = "Approve sending a Google Chat message?"
context = "The agent will post a message into the specified Google Chat space."
allow_edit = true
allow_reject = true

[tool_approvals.set_publish_settings]
summary = "Approve updating Google Form publish settings?"
context = "The agent will change how the selected form is published or shared."
allow_edit = true
allow_reject = true

[tool_approvals.update_doc_headers_footers]
summary = "Approve updating Google Doc headers or footers?"
context = "The agent will modify header or footer content in the document."
allow_edit = true
allow_reject = true

[tool_approvals.update_task]
summary = "Approve updating a Google Task?"
context = "The agent will modify fields on the selected task."
allow_edit = true
allow_reject = true

[tool_approvals.update_task_list]
summary = "Approve renaming or updating a Google Tasks list?"
context = "The agent will modify the metadata of the specified task list."
allow_edit = true
allow_reject = true
